version: 0.2

env:
  variables:
    FORCE_BUILD_API: "false"
    FORCE_BUILD_WEB: "false"
    AWS_DEFAULT_REGION: "ap-northeast-1"
    AWS_REGION: "ap-northeast-1"
    AWS_DOMAIN: ""
    AWS_DOMAIN_OWNER: ""
    CONTAINER_NAME: "hrms-api"
    ECR_ACCOUNT_ID: "644385348015"
    API_REPOSITORY_NAME: "hrms-api"

phases:
  install:
    commands:
      - echo START install
      - CHANGED_API=false
      - CHANGED_WEB=false
      - if [ -d .git ]; then PREV_COMMIT=$(git rev-parse HEAD~1 2>/dev/null || echo ""); echo "Prev commit=$PREV_COMMIT"; if [ -n "$PREV_COMMIT" ]; then CHANGED_LIST=$(git diff --name-only "$PREV_COMMIT" HEAD); else CHANGED_LIST=$(git ls-tree -r --name-only HEAD); fi; echo "Changed files => $CHANGED_LIST"; echo "$CHANGED_LIST" | grep -q '^api/' && CHANGED_API=true || true; echo "$CHANGED_LIST" | grep -q '^web/' && CHANGED_WEB=true || true; else echo "No .git directory -> build all"; CHANGED_API=true; CHANGED_WEB=true; fi
      - if [ "$FORCE_BUILD_API" = "true" ]; then CHANGED_API=true; fi
      - if [ "$FORCE_BUILD_WEB" = "true" ]; then CHANGED_WEB=true; fi
      - echo "CHANGED_API=$CHANGED_API CHANGED_WEB=$CHANGED_WEB"
      - if [ "$CHANGED_WEB" = "true" ]; then cd web && npm ci && cd -; else echo "Skip web install"; fi

  pre_build:
    commands:
      - if [ "$CHANGED_API" = "true" ]; then echo "Login ECR"; REPOSITORY_URI=${ECR_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${API_REPOSITORY_NAME}; IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}; aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${ECR_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com; echo "Get CodeArtifact token"; export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --region $AWS_REGION --domain $AWS_DOMAIN --domain-owner $AWS_DOMAIN_OWNER --query authorizationToken --output text); else echo "Skip API pre_build"; fi

  build:
    commands:
      - if [ "$CHANGED_API" = "true" ]; then cd api && docker build --secret id=codeartifact,env=CODEARTIFACT_AUTH_TOKEN -t $REPOSITORY_URI:$IMAGE_TAG . && docker push $REPOSITORY_URI:$IMAGE_TAG && cd -; fi
      - if [ "$CHANGED_WEB" = "true" ]; then cd web && npm run build && cd -; fi

  post_build:
    commands:
      - if [ "$CHANGED_API" = "true" ]; then printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > api/imagedefinitions.json; fi
      - if [ "$CHANGED_WEB" = "true" ]; then echo "Web build ready for S3 deploy"; fi

artifacts:
  files:
    - api/imagedefinitions.json
    - web/build/**/*
  discard-paths: no

cache:
  paths:
    - 'web/node_modules/**/*'
